# server version
version: v1.5.5

#server config
server:
  port: 5001
#  servlet:
#    context-path: /WeBASE-Node-Manager


spring:
  application:
    # 应用名称
    name: bcos-node-mgr
  profiles:
    # 环境配置
    active: dev

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 127.0.0.1:8848
      discovery:
        # 注册组
        group: DEFAULT_GROUP
        namespace: dev
      config:
        # 配置组
        group: DEFAULT_GROUP
        namespace: dev
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
